name: Docker
on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t pollus-backend
      - name: Log In at docker.pkg.github.com
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push Image to docker.pkg.github.com
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/pollus-backend
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "Publishing $IMAGE_ID:$VERSION"
          docker tag pollus-backend $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
